### ISSUE TITLE
Add references for the various patches

### ISSUE THREAD

**Issue by hadess** [francoism90/linx7#4]
There's no authorship or information about what the various patches do.

I've found this one for the SDHCI PM patch:
http://thread.gmane.org/gmane.linux.kernel.mmc/25081/focus=25087

But nothing for the audio patch, or the RPMB one.

**Comment by francoism90** [comment]
Thanks, I have updated the README.md with the sources I've found them/used as a base.
Unfortunately I'm unable to find any more info about the SDHCI Patch - the patch fixes the freezing issues when using WiFi on the Linx 7.

The audio patch is incomplete, although the audio device is visible, there is no actual output.
When examining the DSDT, it's stated that the audio is addressed at 0 - instead of the default 5.
In the bug report there is one more device that has the same issue.
